export const SHOW_CHECK_OUT_FORM = 'SHOW_CHECK_OUT_FORM'
export const HIDE_CHECK_OUT_FORM = 'HIDE_CHECK_OUT_FORM'
export const SHOW_BUY_NOW_BTN = 'SHOW_BUY_NOW_BTN'
export const HIDE_BUY_NOW_BTN = 'HIDE_BUY_NOW_BTN'